export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_END = 'AJAX_CALL_END';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';



